min_version = "2026.10.4"

[tools]
poetry = "latest"

# matches version in .python-version
python = "3.10"

# needed by speakeasy mockserver
go = "1.22"
"aqua:speakeasy-api/speakeasy" = "latest"
"github:rwjblue-glean/speakeasy-helpers" = "latest"

