"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from glean import Glean, models
import os
from tests.test_client import create_test_http_client


def test_activities_feedback():
    test_http_client = create_test_http_client("feedback")

    with Glean(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=test_http_client,
        bearer_auth=os.getenv("GLEAN_BEARER_AUTH", "value"),
    ) as g_client:
        assert g_client is not None

        g_client.client.activity.feedback(
            feedback1={
                "tracking_tokens": [
                    "trackingTokens",
                ],
                "event": models.Event.VIEW,
            }
        )
