// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PlatformSkillValidationWarning struct {
	// Stable warning code.
	Code string `json:"code"`
	// Human-readable warning message.
	Message string `json:"message"`
}

func (o *PlatformSkillValidationWarning) GetCode() string {
	if o == nil {
		return ""
	}
	return o.Code
}

func (o *PlatformSkillValidationWarning) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}
