"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class AnnouncementChannel(str, Enum):
    r"""This determines whether this is a Social Feed post or a regular announcement."""

    MAIN = "MAIN"
    SOCIAL_FEED = "SOCIAL_FEED"
