"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .gleansearchconfig import GleanSearchConfig, GleanSearchConfigTypedDict
from glean.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AutoAgentActionTypedDict(TypedDict):
    r"""Details of each action within Auto Agent (new actions supported for Auto Agent will be added to properties over time)."""

    action_id: NotRequired[str]
    r"""ID of each action within Auto Agent."""
    glean_search_config: NotRequired[GleanSearchConfigTypedDict]
    r"""Configuration for the Glean Search action."""


class AutoAgentAction(BaseModel):
    r"""Details of each action within Auto Agent (new actions supported for Auto Agent will be added to properties over time)."""

    action_id: Annotated[Optional[str], pydantic.Field(alias="actionId")] = None
    r"""ID of each action within Auto Agent."""

    glean_search_config: Annotated[
        Optional[GleanSearchConfig], pydantic.Field(alias="gleanSearchConfig")
    ] = None
    r"""Configuration for the Glean Search action."""
