"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from glean.errors import collectionerror_1 as errors_collectionerror_1
from glean.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class CollectionError1TypedDict(TypedDict):
    error_code: errors_collectionerror_1.ErrorCode


class CollectionError1(BaseModel):
    error_code: Annotated[
        errors_collectionerror_1.ErrorCode, pydantic.Field(alias="errorCode")
    ]
