"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .executeactiontoolrequest import (
    ExecuteActionToolRequest,
    ExecuteActionToolRequestTypedDict,
)
from glean.types import BaseModel
from glean.utils import FieldMetadata, QueryParamMetadata, RequestMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ExecuteactiontoolRequestRequestTypedDict(TypedDict):
    execute_action_tool_request: ExecuteActionToolRequestTypedDict
    r"""Execute Action Tool request"""
    timezone_offset: NotRequired[int]
    r"""The offset of the client's timezone in minutes from UTC. e.g. PDT is -420 because it's 7 hours behind UTC."""


class ExecuteactiontoolRequestRequest(BaseModel):
    execute_action_tool_request: Annotated[
        ExecuteActionToolRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Execute Action Tool request"""

    timezone_offset: Annotated[
        Optional[int],
        pydantic.Field(alias="timezoneOffset"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""The offset of the client's timezone in minutes from UTC. e.g. PDT is -420 because it's 7 hours behind UTC."""
