"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from glean.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class FileUploadConfigTypedDict(TypedDict):
    r"""Configuration settings for the chat file upload feature"""

    enabled: NotRequired[bool]
    r"""Whether file upload for Chat is enabled for the deployment"""
    max_file_count: NotRequired[int]
    r"""Maximum number of files that can be uploaded in a single turn"""
    max_file_size: NotRequired[int]
    r"""Maximum file size, in bytes, that is allowed for upload"""
    upload_timeout_seconds: NotRequired[int]
    r"""Timeout in seconds for polling the file upload status"""


class FileUploadConfig(BaseModel):
    r"""Configuration settings for the chat file upload feature"""

    enabled: Optional[bool] = None
    r"""Whether file upload for Chat is enabled for the deployment"""

    max_file_count: Annotated[Optional[int], pydantic.Field(alias="maxFileCount")] = (
        None
    )
    r"""Maximum number of files that can be uploaded in a single turn"""

    max_file_size: Annotated[Optional[int], pydantic.Field(alias="maxFileSize")] = None
    r"""Maximum file size, in bytes, that is allowed for upload"""

    upload_timeout_seconds: Annotated[
        Optional[int], pydantic.Field(alias="uploadTimeoutSeconds")
    ] = None
    r"""Timeout in seconds for polling the file upload status"""
