"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .personsuggestionlist import PersonSuggestionList, PersonSuggestionListTypedDict
from glean.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class PeopleSuggestResponseTypedDict(TypedDict):
    suggestions: NotRequired[List[PersonSuggestionListTypedDict]]
    r"""Information about people suggestions for asked categories."""


class PeopleSuggestResponse(BaseModel):
    suggestions: Optional[List[PersonSuggestionList]] = None
    r"""Information about people suggestions for asked categories."""
