"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .peoplesuggestioncategory import PeopleSuggestionCategory
from glean.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class PeopleSuggestRequestTypedDict(TypedDict):
    r"""Includes request params for type of suggestions."""

    categories: List[PeopleSuggestionCategory]
    r"""Categories of data requested. Request can include single or multiple categories."""
    departments: NotRequired[List[str]]
    r"""Departments that the data is requested for. If empty, corresponds to whole company."""


class PeopleSuggestRequest(BaseModel):
    r"""Includes request params for type of suggestions."""

    categories: List[PeopleSuggestionCategory]
    r"""Categories of data requested. Request can include single or multiple categories."""

    departments: Optional[List[str]] = None
    r"""Departments that the data is requested for. If empty, corresponds to whole company."""
