"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from glean.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class RemoveCredentialRequestTypedDict(TypedDict):
    datasource: NotRequired[str]
    r"""the datasource the credential applies to"""
    datasource_instance: NotRequired[str]
    r"""the datasource instance the credential applies to"""
    user: NotRequired[str]
    r"""the user info (email or username for example) for the credential"""


class RemoveCredentialRequest(BaseModel):
    datasource: Optional[str] = None
    r"""the datasource the credential applies to"""

    datasource_instance: Annotated[
        Optional[str], pydantic.Field(alias="datasourceInstance")
    ] = None
    r"""the datasource instance the credential applies to"""

    user: Optional[str] = None
    r"""the user info (email or username for example) for the credential"""
