"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from glean.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ShortcutsConfigTypedDict(TypedDict):
    r"""Configuration settings related to Shortcuts"""

    shortcuts_prefix: NotRequired[str]
    r"""Deployment's prefix for shortcuts."""
    use_external_shortcuts: NotRequired[bool]
    r"""Whether the deployment uses external shortcuts."""


class ShortcutsConfig(BaseModel):
    r"""Configuration settings related to Shortcuts"""

    shortcuts_prefix: Annotated[
        Optional[str], pydantic.Field(alias="shortcutsPrefix")
    ] = None
    r"""Deployment's prefix for shortcuts."""

    use_external_shortcuts: Annotated[
        Optional[bool], pydantic.Field(alias="useExternalShortcuts")
    ] = None
    r"""Whether the deployment uses external shortcuts."""
