"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .temperature import Temperature
from glean.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ThinkConfigTypedDict(TypedDict):
    r"""Configuration for the Think tool."""

    temperature: NotRequired[Temperature]
    r"""The temperature to be used for the LLM."""


class ThinkConfig(BaseModel):
    r"""Configuration for the Think tool."""

    temperature: Optional[Temperature] = None
    r"""The temperature to be used for the LLM."""
