"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from glean.api_client import errors, models, utils
from glean.api_client._hooks import HookContext
from glean.api_client.types import OptionalNullable, UNSET
from glean.api_client.utils import get_security_from_env
from glean.api_client.utils.unmarshal_json_response import unmarshal_json_response
from typing import Mapping, Optional


class Troubleshooting(BaseSDK):
    def post_api_index_v1_debug_datasource_document_events(
        self,
        *,
        datasource: str,
        object_type: str,
        doc_id: str,
        start_date: Optional[str] = None,
        max_events: Optional[int] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.DebugDocumentLifecycleResponse:
        r"""Beta: Get document lifecycle events

        Retrieves lifecycle events for a specific document including upload time, index times and deletions. Rate limited to 1 request per minute per datasource. Currently in beta, might undergo breaking changes without prior notice.


        :param datasource: The datasource to which the document belongs
        :param object_type: Object type of the document to get lifecycle events for.
        :param doc_id: Glean Document ID within the datasource to get lifecycle events for.
        :param start_date: The start date for events to be fetched. Cannot be more than 30 days (default 7 days) in the past.
        :param max_events: Max number of events to be fetched. Cannot be more than 100 (default 20).
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.PostAPIIndexV1DebugDatasourceDocumentEventsRequest(
            datasource=datasource,
            debug_document_lifecycle_request=models.DebugDocumentLifecycleRequest(
                object_type=object_type,
                doc_id=doc_id,
                start_date=start_date,
                max_events=max_events,
            ),
        )

        req = self._build_request(
            method="POST",
            path="/api/index/v1/debug/{datasource}/document/events",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json; charset=UTF-8",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.debug_document_lifecycle_request,
                False,
                False,
                "json",
                models.DebugDocumentLifecycleRequest,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="post_/api/index/v1/debug/{datasource}/document/events",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json; charset=UTF-8"):
            return unmarshal_json_response(
                models.DebugDocumentLifecycleResponse, http_res
            )
        if utils.match_response(http_res, ["400", "401", "429", "4XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.GleanError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.GleanError("API error occurred", http_res, http_res_text)

        raise errors.GleanError("Unexpected response received", http_res)

    async def post_api_index_v1_debug_datasource_document_events_async(
        self,
        *,
        datasource: str,
        object_type: str,
        doc_id: str,
        start_date: Optional[str] = None,
        max_events: Optional[int] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.DebugDocumentLifecycleResponse:
        r"""Beta: Get document lifecycle events

        Retrieves lifecycle events for a specific document including upload time, index times and deletions. Rate limited to 1 request per minute per datasource. Currently in beta, might undergo breaking changes without prior notice.


        :param datasource: The datasource to which the document belongs
        :param object_type: Object type of the document to get lifecycle events for.
        :param doc_id: Glean Document ID within the datasource to get lifecycle events for.
        :param start_date: The start date for events to be fetched. Cannot be more than 30 days (default 7 days) in the past.
        :param max_events: Max number of events to be fetched. Cannot be more than 100 (default 20).
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.PostAPIIndexV1DebugDatasourceDocumentEventsRequest(
            datasource=datasource,
            debug_document_lifecycle_request=models.DebugDocumentLifecycleRequest(
                object_type=object_type,
                doc_id=doc_id,
                start_date=start_date,
                max_events=max_events,
            ),
        )

        req = self._build_request_async(
            method="POST",
            path="/api/index/v1/debug/{datasource}/document/events",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json; charset=UTF-8",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.debug_document_lifecycle_request,
                False,
                False,
                "json",
                models.DebugDocumentLifecycleRequest,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="post_/api/index/v1/debug/{datasource}/document/events",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json; charset=UTF-8"):
            return unmarshal_json_response(
                models.DebugDocumentLifecycleResponse, http_res
            )
        if utils.match_response(http_res, ["400", "401", "429", "4XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.GleanError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.GleanError("API error occurred", http_res, http_res_text)

        raise errors.GleanError("Unexpected response received", http_res)
