"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .gleanbaseerror import GleanBaseError
from typing import Any, TYPE_CHECKING

from glean.api_client.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .accessrequestpermissiondeniedresponse_error import (
        AccessRequestPermissionDeniedResponseError,
        AccessRequestPermissionDeniedResponseErrorData,
    )
    from .collectionerror import CollectionError, CollectionErrorData
    from .errorinforesponse import ErrorInfoResponse, ErrorInfoResponseData
    from .errorresponse import ErrorResponse, ErrorResponseData
    from .gleandataerror import GleanDataError, GleanDataErrorData
    from .gleanerror import GleanError
    from .no_response_error import NoResponseError
    from .platformproblemdetail_error import (
        PlatformProblemDetailError,
        PlatformProblemDetailErrorData,
    )
    from .platformunauthorizedagenttoolsproblem_error import (
        PlatformUnauthorizedAgentToolsProblemError,
        PlatformUnauthorizedAgentToolsProblemErrorData,
    )
    from .responsevalidationerror import ResponseValidationError
    from .unauthorizedagenttoolserror import (
        UnauthorizedAgentToolsError,
        UnauthorizedAgentToolsErrorData,
    )

__all__ = [
    "AccessRequestPermissionDeniedResponseError",
    "AccessRequestPermissionDeniedResponseErrorData",
    "CollectionError",
    "CollectionErrorData",
    "ErrorInfoResponse",
    "ErrorInfoResponseData",
    "ErrorResponse",
    "ErrorResponseData",
    "GleanBaseError",
    "GleanDataError",
    "GleanDataErrorData",
    "GleanError",
    "NoResponseError",
    "PlatformProblemDetailError",
    "PlatformProblemDetailErrorData",
    "PlatformUnauthorizedAgentToolsProblemError",
    "PlatformUnauthorizedAgentToolsProblemErrorData",
    "ResponseValidationError",
    "UnauthorizedAgentToolsError",
    "UnauthorizedAgentToolsErrorData",
]

_dynamic_imports: dict[str, str] = {
    "AccessRequestPermissionDeniedResponseError": ".accessrequestpermissiondeniedresponse_error",
    "AccessRequestPermissionDeniedResponseErrorData": ".accessrequestpermissiondeniedresponse_error",
    "CollectionError": ".collectionerror",
    "CollectionErrorData": ".collectionerror",
    "ErrorInfoResponse": ".errorinforesponse",
    "ErrorInfoResponseData": ".errorinforesponse",
    "ErrorResponse": ".errorresponse",
    "ErrorResponseData": ".errorresponse",
    "GleanDataError": ".gleandataerror",
    "GleanDataErrorData": ".gleandataerror",
    "GleanError": ".gleanerror",
    "NoResponseError": ".no_response_error",
    "PlatformProblemDetailError": ".platformproblemdetail_error",
    "PlatformProblemDetailErrorData": ".platformproblemdetail_error",
    "PlatformUnauthorizedAgentToolsProblemError": ".platformunauthorizedagenttoolsproblem_error",
    "PlatformUnauthorizedAgentToolsProblemErrorData": ".platformunauthorizedagenttoolsproblem_error",
    "ResponseValidationError": ".responsevalidationerror",
    "UnauthorizedAgentToolsError": ".unauthorizedagenttoolserror",
    "UnauthorizedAgentToolsErrorData": ".unauthorizedagenttoolserror",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
