"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
from glean.api_client.errors import GleanBaseError
from glean.api_client.types import BaseModel
import httpx
from typing import Optional


class ErrorInfoResponseData(BaseModel):
    error: str
    r"""Error message describing what went wrong"""
    message: Optional[str] = None
    r"""Additional details about the error"""


@dataclass(unsafe_hash=True)
class ErrorInfoResponse(GleanBaseError):
    r"""Error response for custom metadata operations"""

    data: ErrorInfoResponseData = field(hash=False)

    def __init__(
        self,
        data: ErrorInfoResponseData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
