"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .iconconfig import IconConfig, IconConfigTypedDict
from glean.api_client.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AgentUseCaseInsightTypedDict(TypedDict):
    use_case: NotRequired[str]
    r"""Use case name"""
    run_count: NotRequired[int]
    r"""Total number of runs for this use case over the specified time period."""
    trend: NotRequired[float]
    r"""Percentage change in runs compared to the previous equivalent time period."""
    top_departments: NotRequired[str]
    r"""Comma-separated list of the top departments using this use case."""
    top_agent_id: NotRequired[str]
    r"""ID of the most-used agent for this use case."""
    top_agent_name: NotRequired[str]
    r"""Name of the most-used agent for this use case."""
    top_agent_icon: NotRequired[IconConfigTypedDict]
    r"""Defines how to render an icon"""
    top_agent_is_deleted: NotRequired[bool]
    r"""Indicates whether the top agent has been deleted."""


class AgentUseCaseInsight(BaseModel):
    use_case: Annotated[Optional[str], pydantic.Field(alias="useCase")] = None
    r"""Use case name"""

    run_count: Annotated[Optional[int], pydantic.Field(alias="runCount")] = None
    r"""Total number of runs for this use case over the specified time period."""

    trend: Optional[float] = None
    r"""Percentage change in runs compared to the previous equivalent time period."""

    top_departments: Annotated[
        Optional[str], pydantic.Field(alias="topDepartments")
    ] = None
    r"""Comma-separated list of the top departments using this use case."""

    top_agent_id: Annotated[Optional[str], pydantic.Field(alias="topAgentId")] = None
    r"""ID of the most-used agent for this use case."""

    top_agent_name: Annotated[Optional[str], pydantic.Field(alias="topAgentName")] = (
        None
    )
    r"""Name of the most-used agent for this use case."""

    top_agent_icon: Annotated[
        Optional[IconConfig], pydantic.Field(alias="topAgentIcon")
    ] = None
    r"""Defines how to render an icon"""

    top_agent_is_deleted: Annotated[
        Optional[bool], pydantic.Field(alias="topAgentIsDeleted")
    ] = None
    r"""Indicates whether the top agent has been deleted."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "useCase",
                "runCount",
                "trend",
                "topDepartments",
                "topAgentId",
                "topAgentName",
                "topAgentIcon",
                "topAgentIsDeleted",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    AgentUseCaseInsight.model_rebuild()
except NameError:
    pass
