"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .agentexecutionstatus import AgentExecutionStatus
from .message import Message, MessageTypedDict
from glean.api_client import models
from glean.api_client.types import BaseModel, UNSET_SENTINEL
from pydantic import field_serializer, model_serializer
from typing import Any, Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class AgentRunTypedDict(TypedDict):
    r"""Payload for creating a run. **Important**: If the agent uses an input form trigger, the `input` field is required and must include all fields defined in the form schema. Even fields marked as optional in the UI must be included in the request—use an empty string (`\"\"`) for optional fields without values. Omitting required form fields will result in a 500 error."""

    agent_id: str
    r"""The ID of the agent to run."""
    input: NotRequired[Dict[str, Any]]
    r"""The input to the agent. Required when the agent uses an input form trigger."""
    messages: NotRequired[List[MessageTypedDict]]
    r"""The messages to pass an input to the agent."""
    metadata: NotRequired[Dict[str, Any]]
    r"""The metadata to pass to the agent."""
    status: NotRequired[AgentExecutionStatus]
    r"""The status of the run. One of 'error', 'success'."""


class AgentRun(BaseModel):
    r"""Payload for creating a run. **Important**: If the agent uses an input form trigger, the `input` field is required and must include all fields defined in the form schema. Even fields marked as optional in the UI must be included in the request—use an empty string (`\"\"`) for optional fields without values. Omitting required form fields will result in a 500 error."""

    agent_id: str
    r"""The ID of the agent to run."""

    input: Optional[Dict[str, Any]] = None
    r"""The input to the agent. Required when the agent uses an input form trigger."""

    messages: Optional[List[Message]] = None
    r"""The messages to pass an input to the agent."""

    metadata: Optional[Dict[str, Any]] = None
    r"""The metadata to pass to the agent."""

    status: Optional[AgentExecutionStatus] = None
    r"""The status of the run. One of 'error', 'success'."""

    @field_serializer("status")
    def serialize_status(self, value):
        if isinstance(value, str):
            try:
                return models.AgentExecutionStatus(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["input", "messages", "metadata", "status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
