"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from glean.api_client.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class AuthorizeActionPackResponseTypedDict(TypedDict):
    redirect_url: str
    r"""URL that the customer UI should navigate the end user to in order to begin the third-party OAuth flow.
    After the user consents, control returns to `returnUrl` from the request.

    """


class AuthorizeActionPackResponse(BaseModel):
    redirect_url: Annotated[str, pydantic.Field(alias="redirectUrl")]
    r"""URL that the customer UI should navigate the end user to in order to begin the third-party OAuth flow.
    After the user consents, control returns to `returnUrl` from the request.

    """


try:
    AuthorizeActionPackResponse.model_rebuild()
except NameError:
    pass
