"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from enum import Enum
from glean.api_client import models, utils
from glean.api_client.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import field_serializer, model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AuthConfigType(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The type of authentication being used.
    Use 'OAUTH_*' when Glean calls an external API (e.g., Jira) on behalf of a user to obtain an OAuth token.
    'OAUTH_ADMIN' utilizes an admin token for external API calls on behalf all users.
    'OAUTH_USER' uses individual user tokens for external API calls.
    'DWD' refers to domain wide delegation.

    """

    NONE = "NONE"
    OAUTH_USER = "OAUTH_USER"
    OAUTH_ADMIN = "OAUTH_ADMIN"
    API_KEY = "API_KEY"
    BASIC_AUTH = "BASIC_AUTH"
    DWD = "DWD"


class GrantType(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The type of grant type being used."""

    AUTH_CODE = "AUTH_CODE"
    CLIENT_CREDENTIALS = "CLIENT_CREDENTIALS"


class AuthConfigStatus(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Auth status of the tool."""

    AWAITING_AUTH = "AWAITING_AUTH"
    AUTHORIZED = "AUTHORIZED"
    AUTH_DISABLED = "AUTH_DISABLED"


class TokenEndpointAuthMethod(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The OAuth 2.0 token endpoint authentication method (RFC 7591). Determines how the client authenticates when exchanging an authorization code for a token. Values use lowercase to match the OAuth 2.0 wire format (RFC 7591 Section 2)."""

    # Send client_id and client_secret as form fields in the token request body.
    CLIENT_SECRET_POST = "client_secret_post"
    # Send client_id and client_secret via the HTTP Basic Authorization header.
    CLIENT_SECRET_BASIC = "client_secret_basic"
    # Public client - omit the client secret and authenticate with the PKCE code_verifier only.
    NONE = "none"
    # Authenticate with a JWT client assertion signed by the client's private key (RFC 7523 Section 2.2 / OIDC Core Section 9). Requires a key pair pre-registered with the authorization server.
    PRIVATE_KEY_JWT = "private_key_jwt"


class AuthHeaderType(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Defines the header structure for sending the API key or token to the server. Defaults to AUTHORIZATION_BEARER. Select the specific header format the server expects for transmitting the key."""

    # Sends \"Authorization: Bearer <key>\".
    AUTHORIZATION_BEARER = "AUTHORIZATION_BEARER"
    # Sends \"Authorization: Token <key>\".
    AUTHORIZATION_TOKEN = "AUTHORIZATION_TOKEN"
    # Sends \"Authorization: ApiKey <key>\".
    AUTHORIZATION_API_KEY = "AUTHORIZATION_API_KEY"
    # Sends \"X-API-Key: <key>\". No Authorization header is sent.
    X_API_KEY = "X_API_KEY"


class AuthConfigTypedDict(TypedDict):
    r"""Config for tool's authentication method."""

    is_on_prem: NotRequired[bool]
    r"""Whether or not this tool is hosted on-premise."""
    uses_central_auth: NotRequired[bool]
    r"""Whether or not this uses central auth."""
    type: NotRequired[AuthConfigType]
    r"""The type of authentication being used.
    Use 'OAUTH_*' when Glean calls an external API (e.g., Jira) on behalf of a user to obtain an OAuth token.
    'OAUTH_ADMIN' utilizes an admin token for external API calls on behalf all users.
    'OAUTH_USER' uses individual user tokens for external API calls.
    'DWD' refers to domain wide delegation.

    """
    grant_type: NotRequired[GrantType]
    r"""The type of grant type being used."""
    status: NotRequired[AuthConfigStatus]
    r"""Auth status of the tool."""
    client_url: NotRequired[str]
    r"""The URL where users will be directed to start the OAuth flow."""
    scopes: NotRequired[List[str]]
    r"""A list of strings denoting the different scopes or access levels required by the tool."""
    audiences: NotRequired[List[str]]
    r"""A list of strings denoting the different audience which can access the tool."""
    authorization_url: NotRequired[str]
    r"""The OAuth provider's endpoint, where access tokens are requested."""
    resource: NotRequired[str]
    r"""The OAuth 2.0 Resource Indicator (RFC 8707) for the protected resource. Discovered from Protected Resource Metadata (RFC 9728) during DCR. Included in authorization and token exchange requests when present."""
    token_endpoint_auth_method: NotRequired[TokenEndpointAuthMethod]
    r"""The OAuth 2.0 token endpoint authentication method (RFC 7591). Determines how the client authenticates when exchanging an authorization code for a token. Values use lowercase to match the OAuth 2.0 wire format (RFC 7591 Section 2)."""
    auth_header_type: NotRequired[AuthHeaderType]
    r"""Defines the header structure for sending the API key or token to the server. Defaults to AUTHORIZATION_BEARER. Select the specific header format the server expects for transmitting the key."""
    last_authorized_at: NotRequired[datetime]
    r"""The time the tool was last authorized in ISO format (ISO 8601)."""


class AuthConfig(BaseModel):
    r"""Config for tool's authentication method."""

    is_on_prem: Annotated[Optional[bool], pydantic.Field(alias="isOnPrem")] = None
    r"""Whether or not this tool is hosted on-premise."""

    uses_central_auth: Annotated[
        Optional[bool], pydantic.Field(alias="usesCentralAuth")
    ] = None
    r"""Whether or not this uses central auth."""

    type: Optional[AuthConfigType] = None
    r"""The type of authentication being used.
    Use 'OAUTH_*' when Glean calls an external API (e.g., Jira) on behalf of a user to obtain an OAuth token.
    'OAUTH_ADMIN' utilizes an admin token for external API calls on behalf all users.
    'OAUTH_USER' uses individual user tokens for external API calls.
    'DWD' refers to domain wide delegation.

    """

    grant_type: Annotated[Optional[GrantType], pydantic.Field(alias="grantType")] = None
    r"""The type of grant type being used."""

    status: Optional[AuthConfigStatus] = None
    r"""Auth status of the tool."""

    client_url: Optional[str] = None
    r"""The URL where users will be directed to start the OAuth flow."""

    scopes: Optional[List[str]] = None
    r"""A list of strings denoting the different scopes or access levels required by the tool."""

    audiences: Optional[List[str]] = None
    r"""A list of strings denoting the different audience which can access the tool."""

    authorization_url: Optional[str] = None
    r"""The OAuth provider's endpoint, where access tokens are requested."""

    resource: Optional[str] = None
    r"""The OAuth 2.0 Resource Indicator (RFC 8707) for the protected resource. Discovered from Protected Resource Metadata (RFC 9728) during DCR. Included in authorization and token exchange requests when present."""

    token_endpoint_auth_method: Optional[TokenEndpointAuthMethod] = None
    r"""The OAuth 2.0 token endpoint authentication method (RFC 7591). Determines how the client authenticates when exchanging an authorization code for a token. Values use lowercase to match the OAuth 2.0 wire format (RFC 7591 Section 2)."""

    auth_header_type: Annotated[
        Optional[AuthHeaderType], pydantic.Field(alias="authHeaderType")
    ] = None
    r"""Defines the header structure for sending the API key or token to the server. Defaults to AUTHORIZATION_BEARER. Select the specific header format the server expects for transmitting the key."""

    last_authorized_at: Annotated[
        Optional[datetime], pydantic.Field(alias="lastAuthorizedAt")
    ] = None
    r"""The time the tool was last authorized in ISO format (ISO 8601)."""

    @field_serializer("type")
    def serialize_type(self, value):
        if isinstance(value, str):
            try:
                return models.AuthConfigType(value)
            except ValueError:
                return value
        return value

    @field_serializer("grant_type")
    def serialize_grant_type(self, value):
        if isinstance(value, str):
            try:
                return models.GrantType(value)
            except ValueError:
                return value
        return value

    @field_serializer("status")
    def serialize_status(self, value):
        if isinstance(value, str):
            try:
                return models.AuthConfigStatus(value)
            except ValueError:
                return value
        return value

    @field_serializer("token_endpoint_auth_method")
    def serialize_token_endpoint_auth_method(self, value):
        if isinstance(value, str):
            try:
                return models.TokenEndpointAuthMethod(value)
            except ValueError:
                return value
        return value

    @field_serializer("auth_header_type")
    def serialize_auth_header_type(self, value):
        if isinstance(value, str):
            try:
                return models.AuthHeaderType(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "isOnPrem",
                "usesCentralAuth",
                "type",
                "grantType",
                "status",
                "client_url",
                "scopes",
                "audiences",
                "authorization_url",
                "resource",
                "token_endpoint_auth_method",
                "authHeaderType",
                "lastAuthorizedAt",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    AuthConfig.model_rebuild()
except NameError:
    pass
