"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from glean.api_client import models, utils
from glean.api_client.types import BaseModel, UNSET_SENTINEL
from pydantic import field_serializer, model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class Provider(str, Enum, metaclass=utils.OpenEnumMeta):
    ZOOM = "ZOOM"
    HANGOUTS = "HANGOUTS"


class ConferenceDataSource(str, Enum, metaclass=utils.OpenEnumMeta):
    NATIVE_CONFERENCE = "NATIVE_CONFERENCE"
    LOCATION = "LOCATION"
    DESCRIPTION = "DESCRIPTION"


class ConferenceDataTypedDict(TypedDict):
    provider: Provider
    uri: str
    r"""A permalink for the conference."""
    source: NotRequired[ConferenceDataSource]


class ConferenceData(BaseModel):
    provider: Provider

    uri: str
    r"""A permalink for the conference."""

    source: Optional[ConferenceDataSource] = None

    @field_serializer("provider")
    def serialize_provider(self, value):
        if isinstance(value, str):
            try:
                return models.Provider(value)
            except ValueError:
                return value
        return value

    @field_serializer("source")
    def serialize_source(self, value):
        if isinstance(value, str):
            try:
                return models.ConferenceDataSource(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["source"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
