"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from glean.api_client.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CurrentActiveUsersTypedDict(TypedDict):
    monthly_active_users: NotRequired[int]
    r"""Number of current Monthly Active Users."""
    weekly_active_users: NotRequired[int]
    r"""Number of current Weekly Active Users."""


class CurrentActiveUsers(BaseModel):
    monthly_active_users: Annotated[
        Optional[int], pydantic.Field(alias="monthlyActiveUsers")
    ] = None
    r"""Number of current Monthly Active Users."""

    weekly_active_users: Annotated[
        Optional[int], pydantic.Field(alias="weeklyActiveUsers")
    ] = None
    r"""Number of current Weekly Active Users."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["monthlyActiveUsers", "weeklyActiveUsers"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    CurrentActiveUsers.model_rebuild()
except NameError:
    pass
