"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dlpissuestatus import DlpIssueStatus
from .dlpseverity import DlpSeverity
from .timerangefilter import TimeRangeFilter, TimeRangeFilterTypedDict
from glean.api_client.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class DlpIssueFilterTypedDict(TypedDict):
    r"""Filter for DLP issues. Includes document-level filters and issue-specific filters."""

    search_text: NotRequired[str]
    r"""Text to search for in issue fields."""
    statuses: NotRequired[List[DlpIssueStatus]]
    r"""Filter by one or more issue statuses."""
    assignee_id: NotRequired[str]
    r"""Filter by assignee user ID."""
    info_type: NotRequired[str]
    regex_id: NotRequired[str]
    report_ids: NotRequired[List[str]]
    r"""Filter by one or more report/policy IDs."""
    doc_id: NotRequired[str]
    datasource: NotRequired[str]
    visibility: NotRequired[str]
    severities: NotRequired[List[DlpSeverity]]
    r"""Filter by one or more severity levels."""
    time_range: NotRequired[TimeRangeFilterTypedDict]


class DlpIssueFilter(BaseModel):
    r"""Filter for DLP issues. Includes document-level filters and issue-specific filters."""

    search_text: Annotated[Optional[str], pydantic.Field(alias="searchText")] = None
    r"""Text to search for in issue fields."""

    statuses: Optional[List[DlpIssueStatus]] = None
    r"""Filter by one or more issue statuses."""

    assignee_id: Annotated[Optional[str], pydantic.Field(alias="assigneeId")] = None
    r"""Filter by assignee user ID."""

    info_type: Annotated[Optional[str], pydantic.Field(alias="infoType")] = None

    regex_id: Annotated[Optional[str], pydantic.Field(alias="regexId")] = None

    report_ids: Annotated[Optional[List[str]], pydantic.Field(alias="reportIds")] = None
    r"""Filter by one or more report/policy IDs."""

    doc_id: Annotated[Optional[str], pydantic.Field(alias="docId")] = None

    datasource: Optional[str] = None

    visibility: Optional[str] = None

    severities: Optional[List[DlpSeverity]] = None
    r"""Filter by one or more severity levels."""

    time_range: Annotated[
        Optional[TimeRangeFilter], pydantic.Field(alias="timeRange")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "searchText",
                "statuses",
                "assigneeId",
                "infoType",
                "regexId",
                "reportIds",
                "docId",
                "datasource",
                "visibility",
                "severities",
                "timeRange",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    DlpIssueFilter.model_rebuild()
except NameError:
    pass
