"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from glean.api_client.types import BaseModel
from glean.api_client.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class GetToolServerAuthStatusRequestTypedDict(TypedDict):
    server_id: str
    r"""Unique identifier of the tool server."""


class GetToolServerAuthStatusRequest(BaseModel):
    server_id: Annotated[
        str,
        pydantic.Field(alias="serverId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Unique identifier of the tool server."""
