"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from glean.api_client import utils


class ImportAgentStatus(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Outcome of the import for the target agent."""

    CREATED = "CREATED"
    UPDATED = "UPDATED"
    DRAFT_PREVIEW = "DRAFT_PREVIEW"
