"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .importagentsyncmode import ImportAgentSyncMode
from glean.api_client.types import BaseModel, UNSET_SENTINEL
from glean.api_client.utils import FieldMetadata, MultipartFormMetadata
import io
import pydantic
from pydantic import model_serializer
from typing import IO, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


class BundleTypedDict(TypedDict):
    file_name: str
    content: Union[bytes, IO[bytes], io.IOBase]
    content_type: NotRequired[str]


class Bundle(BaseModel):
    file_name: Annotated[
        str, pydantic.Field(alias="fileName"), FieldMetadata(multipart=True)
    ]

    content: Annotated[
        Union[bytes, IO[bytes], io.IOBase],
        pydantic.Field(alias=""),
        FieldMetadata(multipart=MultipartFormMetadata(content=True)),
    ]

    content_type: Annotated[
        Optional[str],
        pydantic.Field(alias="Content-Type"),
        FieldMetadata(multipart=True),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["contentType"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ImportAgentRequestTypedDict(TypedDict):
    bundle: BundleTypedDict
    r"""Zip of the agent folder (spec.yaml, instructions.md, skills/, subagents/) with symlinks dereferenced.

    """
    git_commit_sha: NotRequired[str]
    r"""Optional Git commit SHA to associate with this import."""
    git_author_id: NotRequired[str]
    r"""Optional VCS commit author ID to associate with this import."""
    commit_message: NotRequired[str]
    r"""Optional commit message for the imported version."""
    sync_mode: NotRequired[ImportAgentSyncMode]
    r"""Whether the imported version is staged (saved without updating the live version) or published directly to the live version.

    """
    is_draft: NotRequired[bool]
    r"""Deprecated. Draft mutation semantics are not supported for transient previews. Use transient and parentWorkflowId instead.

    """


class ImportAgentRequest(BaseModel):
    bundle: Annotated[Bundle, FieldMetadata(multipart=MultipartFormMetadata(file=True))]
    r"""Zip of the agent folder (spec.yaml, instructions.md, skills/, subagents/) with symlinks dereferenced.

    """

    git_commit_sha: Annotated[
        Optional[str],
        pydantic.Field(alias="gitCommitSha"),
        FieldMetadata(multipart=True),
    ] = None
    r"""Optional Git commit SHA to associate with this import."""

    git_author_id: Annotated[
        Optional[str],
        pydantic.Field(alias="gitAuthorId"),
        FieldMetadata(multipart=True),
    ] = None
    r"""Optional VCS commit author ID to associate with this import."""

    commit_message: Annotated[
        Optional[str],
        pydantic.Field(alias="commitMessage"),
        FieldMetadata(multipart=True),
    ] = None
    r"""Optional commit message for the imported version."""

    sync_mode: Annotated[
        Optional[ImportAgentSyncMode],
        pydantic.Field(alias="syncMode"),
        FieldMetadata(multipart=True),
    ] = None
    r"""Whether the imported version is staged (saved without updating the live version) or published directly to the live version.

    """

    is_draft: Annotated[
        Optional[bool], pydantic.Field(alias="isDraft"), FieldMetadata(multipart=True)
    ] = None
    r"""Deprecated. Draft mutation semantics are not supported for transient previews. Use transient and parentWorkflowId instead.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["gitCommitSha", "gitAuthorId", "commitMessage", "syncMode", "isDraft"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
