"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from glean.api_client.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class McpServerBreakdownTypedDict(TypedDict):
    server: NotRequired[str]
    r"""MCP server name."""
    total_calls: NotRequired[int]
    r"""Total number of MCP calls for this server in the specified time period."""
    active_users: NotRequired[int]
    r"""Total number of active users for this server in the specified time period."""
    host_applications: NotRequired[List[str]]
    r"""Host applications using this server in the specified time period."""


class McpServerBreakdown(BaseModel):
    server: Optional[str] = None
    r"""MCP server name."""

    total_calls: Annotated[Optional[int], pydantic.Field(alias="totalCalls")] = None
    r"""Total number of MCP calls for this server in the specified time period."""

    active_users: Annotated[Optional[int], pydantic.Field(alias="activeUsers")] = None
    r"""Total number of active users for this server in the specified time period."""

    host_applications: Annotated[
        Optional[List[str]], pydantic.Field(alias="hostApplications")
    ] = None
    r"""Host applications using this server in the specified time period."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["server", "totalCalls", "activeUsers", "hostApplications"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    McpServerBreakdown.model_rebuild()
except NameError:
    pass
