"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .platformpersonreference import (
    PlatformPersonReference,
    PlatformPersonReferenceTypedDict,
)
from .platformskillorigin import PlatformSkillOrigin
from .platformskillsourceprovenance import (
    PlatformSkillSourceProvenance,
    PlatformSkillSourceProvenanceTypedDict,
)
from .platformskillstatus import PlatformSkillStatus
from datetime import datetime
from glean.api_client import models
from glean.api_client.types import BaseModel, UNSET_SENTINEL
from pydantic import field_serializer, model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class PlatformSkillTypedDict(TypedDict):
    id: str
    r"""Glean skill ID."""
    display_name: str
    r"""Human-readable skill name."""
    description: str
    r"""Human-readable skill description."""
    latest_version: int
    r"""Latest major version number for the skill."""
    latest_minor_version: int
    r"""Latest minor version number for the skill."""
    status: PlatformSkillStatus
    r"""Current skill status."""
    origin: PlatformSkillOrigin
    r"""Source category for the skill."""
    owner: PlatformPersonReferenceTypedDict
    r"""A lightweight reference to a person, used where a payload merely points at someone."""
    created_at: datetime
    r"""Time the skill was created."""
    updated_at: datetime
    r"""Time the skill was last updated."""
    source_provenance: NotRequired[PlatformSkillSourceProvenanceTypedDict]


class PlatformSkill(BaseModel):
    id: str
    r"""Glean skill ID."""

    display_name: str
    r"""Human-readable skill name."""

    description: str
    r"""Human-readable skill description."""

    latest_version: int
    r"""Latest major version number for the skill."""

    latest_minor_version: int
    r"""Latest minor version number for the skill."""

    status: PlatformSkillStatus
    r"""Current skill status."""

    origin: PlatformSkillOrigin
    r"""Source category for the skill."""

    owner: PlatformPersonReference
    r"""A lightweight reference to a person, used where a payload merely points at someone."""

    created_at: datetime
    r"""Time the skill was created."""

    updated_at: datetime
    r"""Time the skill was last updated."""

    source_provenance: Optional[PlatformSkillSourceProvenance] = None

    @field_serializer("status")
    def serialize_status(self, value):
        if isinstance(value, str):
            try:
                return models.PlatformSkillStatus(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["source_provenance"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
