"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .platformchatcustomentitysource import (
    PlatformChatCustomEntitySource,
    PlatformChatCustomEntitySourceTypedDict,
)
from .platformchatdocumentsource import (
    PlatformChatDocumentSource,
    PlatformChatDocumentSourceTypedDict,
)
from .platformchatfilesource import (
    PlatformChatFileSource,
    PlatformChatFileSourceTypedDict,
)
from .platformchatpersonsource import (
    PlatformChatPersonSource,
    PlatformChatPersonSourceTypedDict,
)
from glean.api_client.utils import get_discriminator
from pydantic import Discriminator, Tag
from typing import Union
from typing_extensions import Annotated, TypeAliasType


PlatformChatCitationSourceTypedDict = TypeAliasType(
    "PlatformChatCitationSourceTypedDict",
    Union[
        PlatformChatPersonSourceTypedDict,
        PlatformChatFileSourceTypedDict,
        PlatformChatCustomEntitySourceTypedDict,
        PlatformChatDocumentSourceTypedDict,
    ],
)
r"""Four-variant citation source union."""


PlatformChatCitationSource = Annotated[
    Union[
        Annotated[PlatformChatDocumentSource, Tag("DOCUMENT")],
        Annotated[PlatformChatPersonSource, Tag("PERSON")],
        Annotated[PlatformChatFileSource, Tag("FILE")],
        Annotated[PlatformChatCustomEntitySource, Tag("CUSTOM_ENTITY")],
    ],
    Discriminator(lambda m: get_discriminator(m, "type", "type")),
]
r"""Four-variant citation source union."""
