"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from glean.api_client import utils


class PlatformTriggerStatus(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Current trigger lifecycle state."""

    ENABLED = "ENABLED"
    DISABLED = "DISABLED"
