"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .platformcontenttype import PlatformContentType
from glean.api_client.types import BaseModel
from typing_extensions import TypedDict


class PlatformMessageTextBlockTypedDict(TypedDict):
    text: str
    r"""Text content."""
    type: PlatformContentType


class PlatformMessageTextBlock(BaseModel):
    text: str
    r"""Text content."""

    type: PlatformContentType
