"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .platformchatoutputmessage import (
    PlatformChatOutputMessage,
    PlatformChatOutputMessageTypedDict,
)
from datetime import datetime
from enum import Enum
from glean.api_client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List
from typing_extensions import NotRequired, TypedDict


class Object(str, Enum):
    RESPONSE = "RESPONSE"


class PlatformChatCompletedResponseStatus(str, Enum):
    COMPLETED = "COMPLETED"


class PlatformChatCompletedResponseTypedDict(TypedDict):
    id: str
    r"""Platform-owned, non-persisted response envelope identifier in `resp_<uuid>` form. The same identifier is used for every event in one streamed response.

    """
    object: Object
    created_at: datetime
    r"""RFC 3339 UTC timestamp when the response was created."""
    status: PlatformChatCompletedResponseStatus
    output: List[PlatformChatOutputMessageTypedDict]
    store: bool
    request_id: str
    conversation_id: NotRequired[Nullable[str]]
    r"""Present when the interaction was persisted."""


class PlatformChatCompletedResponse(BaseModel):
    id: str
    r"""Platform-owned, non-persisted response envelope identifier in `resp_<uuid>` form. The same identifier is used for every event in one streamed response.

    """

    object: Object

    created_at: datetime
    r"""RFC 3339 UTC timestamp when the response was created."""

    status: PlatformChatCompletedResponseStatus

    output: List[PlatformChatOutputMessage]

    store: bool

    request_id: str

    conversation_id: OptionalNullable[str] = UNSET
    r"""Present when the interaction was persisted."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["conversation_id"])
        nullable_fields = set(["conversation_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
