"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .platformskillsourcepreviewstreamerror import (
    PlatformSkillSourcePreviewStreamError,
    PlatformSkillSourcePreviewStreamErrorTypedDict,
)
from glean.api_client.types import BaseModel, UNSET_SENTINEL
from glean.api_client.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PlatformSkillSourcePreviewStreamErrorServerSentEventTypedDict(TypedDict):
    data: PlatformSkillSourcePreviewStreamErrorTypedDict
    r"""Terminal failure event carrying the failure as a problem detail. Most GitHub authorization failures return HTTP 422 before the stream opens. If authorization fails after the stream opens, `error.code` is `tools_unauthorized` and `authentication_suggestions` is present."""
    id: NotRequired[str]
    event: Literal["ERROR"]


class PlatformSkillSourcePreviewStreamErrorServerSentEvent(BaseModel):
    data: PlatformSkillSourcePreviewStreamError
    r"""Terminal failure event carrying the failure as a problem detail. Most GitHub authorization failures return HTTP 422 before the stream opens. If authorization fails after the stream opens, `error.code` is `tools_unauthorized` and `authentication_suggestions` is present."""

    id: Optional[str] = None

    EVENT: Annotated[
        Annotated[Literal["ERROR"], AfterValidator(validate_const("ERROR"))],
        pydantic.Field(alias="event"),
    ] = "ERROR"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    PlatformSkillSourcePreviewStreamErrorServerSentEvent.model_rebuild()
except NameError:
    pass
