"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from glean.api_client.types import BaseModel
from typing_extensions import TypedDict


class PlatformDepartmentTypedDict(TypedDict):
    r"""A department in the Glean directory."""

    department_id: str
    r"""Opaque department ID. The users and departments APIs return the same ID for the same department. A renamed department gets a new ID.

    """
    display_name: str
    r"""Department name, exactly as the directory stores it."""
    is_active: bool
    r"""Whether at least one active user belongs to the department. A department that belongs only to inactive users, or that only a usage limit names, is inactive.

    """


class PlatformDepartment(BaseModel):
    r"""A department in the Glean directory."""

    department_id: str
    r"""Opaque department ID. The users and departments APIs return the same ID for the same department. A renamed department gets a new ID.

    """

    display_name: str
    r"""Department name, exactly as the directory stores it."""

    is_active: bool
    r"""Whether at least one active user belongs to the department. A department that belongs only to inactive users, or that only a usage limit names, is inactive.

    """
