"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .platformagentruncreaterequest import (
    PlatformAgentRunCreateRequest,
    PlatformAgentRunCreateRequestTypedDict,
)
from .platformagentrunwaitresponse import (
    PlatformAgentRunWaitResponse,
    PlatformAgentRunWaitResponseTypedDict,
)
from glean.api_client.types import BaseModel
from glean.api_client.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class PlatformAgentsCreateRunRequestTypedDict(TypedDict):
    agent_id: str
    r"""ID of the agent to run."""
    platform_agent_run_create_request: PlatformAgentRunCreateRequestTypedDict


class PlatformAgentsCreateRunRequest(BaseModel):
    agent_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""ID of the agent to run."""

    platform_agent_run_create_request: Annotated[
        PlatformAgentRunCreateRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


PlatformAgentsCreateRunResponseTypedDict = TypeAliasType(
    "PlatformAgentsCreateRunResponseTypedDict",
    Union[PlatformAgentRunWaitResponseTypedDict, str],
)


PlatformAgentsCreateRunResponse = TypeAliasType(
    "PlatformAgentsCreateRunResponse", Union[PlatformAgentRunWaitResponse, str]
)
