"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .platformskill import PlatformSkill, PlatformSkillTypedDict
from glean.api_client.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class PlatformSkillImportResponseTypedDict(TypedDict):
    skills: List[PlatformSkillTypedDict]
    r"""Independently persisted skills in request order."""
    request_id: str
    r"""Platform-generated request ID for support correlation."""


class PlatformSkillImportResponse(BaseModel):
    skills: List[PlatformSkill]
    r"""Independently persisted skills in request order."""

    request_id: str
    r"""Platform-generated request ID for support correlation."""
