"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .platformskillsourcepreviewresponse import (
    PlatformSkillSourcePreviewResponse,
    PlatformSkillSourcePreviewResponseTypedDict,
)
from enum import Enum
from glean.api_client.types import BaseModel
from typing_extensions import TypedDict


class PlatformSkillSourcePreviewStreamResultType(str, Enum):
    r"""Event type, also sent as the SSE `event` name."""

    RESULT = "RESULT"


class PlatformSkillSourcePreviewStreamResultTypedDict(TypedDict):
    r"""Terminal success event carrying the fully assembled preview."""

    type: PlatformSkillSourcePreviewStreamResultType
    r"""Event type, also sent as the SSE `event` name."""
    response: PlatformSkillSourcePreviewResponseTypedDict


class PlatformSkillSourcePreviewStreamResult(BaseModel):
    r"""Terminal success event carrying the fully assembled preview."""

    type: PlatformSkillSourcePreviewStreamResultType
    r"""Event type, also sent as the SSE `event` name."""

    response: PlatformSkillSourcePreviewResponse
