"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .platformresult import PlatformResult, PlatformResultTypedDict
from glean.api_client.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List
from typing_extensions import TypedDict


class PlatformSearchResponseTypedDict(TypedDict):
    results: List[PlatformResultTypedDict]
    r"""Ordered list of search results."""
    has_more: bool
    r"""Indicates whether additional pages of results are available."""
    next_cursor: Nullable[str]
    r"""Opaque token to pass as `cursor` in the next request."""
    request_id: str
    r"""Platform-generated request ID for support correlation."""


class PlatformSearchResponse(BaseModel):
    results: List[PlatformResult]
    r"""Ordered list of search results."""

    has_more: bool
    r"""Indicates whether additional pages of results are available."""

    next_cursor: Nullable[str]
    r"""Opaque token to pass as `cursor` in the next request."""

    request_id: str
    r"""Platform-generated request ID for support correlation."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
