"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .platformskillupdaterequest import (
    PlatformSkillUpdateRequest,
    PlatformSkillUpdateRequestTypedDict,
)
from glean.api_client.types import BaseModel
from glean.api_client.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class PlatformSkillsUpdateRequestTypedDict(TypedDict):
    skill_id: str
    r"""Glean skill ID."""
    platform_skill_update_request: PlatformSkillUpdateRequestTypedDict


class PlatformSkillsUpdateRequest(BaseModel):
    skill_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Glean skill ID."""

    platform_skill_update_request: Annotated[
        PlatformSkillUpdateRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
