"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from glean.api_client.types import BaseModel
from typing_extensions import TypedDict


class PlatformWarningTypedDict(TypedDict):
    r"""Non-blocking warning attached to a successful Platform response."""

    code: str
    r"""Open snake_case warning code. Clients must tolerate unknown values; the set of codes is not a closed enum.

    """
    message: str
    r"""Human-readable warning message."""


class PlatformWarning(BaseModel):
    r"""Non-blocking warning attached to a successful Platform response."""

    code: str
    r"""Open snake_case warning code. Clients must tolerate unknown values; the set of codes is not a closed enum.

    """

    message: str
    r"""Human-readable warning message."""
