"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from glean.api_client.types import BaseModel
from typing_extensions import TypedDict


class PlatformChatTextFormatType(str, Enum):
    r"""Discriminator. Must be TEXT."""

    TEXT = "TEXT"


class PlatformChatTextFormatTypedDict(TypedDict):
    r"""Unconstrained plain-text assistant output."""

    type: PlatformChatTextFormatType
    r"""Discriminator. Must be TEXT."""


class PlatformChatTextFormat(BaseModel):
    r"""Unconstrained plain-text assistant output."""

    type: PlatformChatTextFormatType
    r"""Discriminator. Must be TEXT."""
