"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from glean.api_client.types import BaseModel
from typing_extensions import TypedDict


class PlatformUserManagerTypedDict(TypedDict):
    r"""The user that another user reports to."""

    user_id: str
    r"""Opaque canonical Glean user ID of the manager."""
    display_name: str
    r"""The name that Glean shows for the manager."""


class PlatformUserManager(BaseModel):
    r"""The user that another user reports to."""

    user_id: str
    r"""Opaque canonical Glean user ID of the manager."""

    display_name: str
    r"""The name that Glean shows for the manager."""
