"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from glean.api_client.types import BaseModel
from typing_extensions import TypedDict


class PlatformTriggerAuthType(str, Enum):
    r"""Credential scheme."""

    BEARER = "BEARER"


class PlatformTriggerAuthOutputTypedDict(TypedDict):
    r"""Optional caller credential sent as an HTTP auth header on each delivery, in addition to the HMAC signature. Lets the receiving endpoint authenticate the request. On update, omit `auth` to preserve the existing credential; there is no in-place removal — recreate the trigger to remove auth."""

    type: PlatformTriggerAuthType
    r"""Credential scheme."""


class PlatformTriggerAuthOutput(BaseModel):
    r"""Optional caller credential sent as an HTTP auth header on each delivery, in addition to the HMAC signature. Lets the receiving endpoint authenticate the request. On update, omit `auth` to preserve the existing credential; there is no in-place removal — recreate the trigger to remove auth."""

    type: PlatformTriggerAuthType
    r"""Credential scheme."""


class PlatformTriggerAuthTypedDict(TypedDict):
    r"""Optional caller credential sent as an HTTP auth header on each delivery, in addition to the HMAC signature. Lets the receiving endpoint authenticate the request. On update, omit `auth` to preserve the existing credential; there is no in-place removal — recreate the trigger to remove auth."""

    type: PlatformTriggerAuthType
    r"""Credential scheme."""
    secret: str
    r"""Secret credential value. Write-only; never returned on reads."""


class PlatformTriggerAuth(BaseModel):
    r"""Optional caller credential sent as an HTTP auth header on each delivery, in addition to the HMAC signature. Lets the receiving endpoint authenticate the request. On update, omit `auth` to preserve the existing credential; there is no in-place removal — recreate the trigger to remove auth."""

    type: PlatformTriggerAuthType
    r"""Credential scheme."""

    secret: str
    r"""Secret credential value. Write-only; never returned on reads."""
