"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .platformproblemdetailcode import PlatformProblemDetailCode
from .platformproblemdetailerror import (
    PlatformProblemDetailError,
    PlatformProblemDetailErrorTypedDict,
)
from glean.api_client import models
from glean.api_client.types import BaseModel, UNSET_SENTINEL
from pydantic import field_serializer, model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class PlatformProblemDetailTypedDict(TypedDict):
    r"""Error response following RFC 9457, extended with `code` and `documentation_url` for machine-readable classification and self-service remediation."""

    type: str
    r"""URI identifying the error type."""
    title: str
    r"""Short, human-readable summary of the error."""
    status: int
    r"""HTTP status code mirrored from the response."""
    detail: str
    r"""Human-readable explanation specific to this occurrence."""
    code: PlatformProblemDetailCode
    r"""Stable machine-readable error code."""
    request_id: str
    r"""Platform-generated request ID for support correlation."""
    documentation_url: NotRequired[str]
    r"""Direct URL to documentation for this error code."""
    errors: NotRequired[List[PlatformProblemDetailErrorTypedDict]]
    r"""Field-level validation problems, one entry per offending field."""


class PlatformProblemDetail(BaseModel):
    r"""Error response following RFC 9457, extended with `code` and `documentation_url` for machine-readable classification and self-service remediation."""

    type: str
    r"""URI identifying the error type."""

    title: str
    r"""Short, human-readable summary of the error."""

    status: int
    r"""HTTP status code mirrored from the response."""

    detail: str
    r"""Human-readable explanation specific to this occurrence."""

    code: PlatformProblemDetailCode
    r"""Stable machine-readable error code."""

    request_id: str
    r"""Platform-generated request ID for support correlation."""

    documentation_url: Optional[str] = None
    r"""Direct URL to documentation for this error code."""

    errors: Optional[List[PlatformProblemDetailError]] = None
    r"""Field-level validation problems, one entry per offending field."""

    @field_serializer("code")
    def serialize_code(self, value):
        if isinstance(value, str):
            try:
                return models.PlatformProblemDetailCode(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["documentation_url", "errors"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
