"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .platformchatstreamoutputtextdone import (
    PlatformChatStreamOutputTextDone,
    PlatformChatStreamOutputTextDoneTypedDict,
)
from glean.api_client.types import BaseModel, UNSET_SENTINEL
from glean.api_client.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PlatformChatStreamOutputTextDoneServerSentEventTypedDict(TypedDict):
    data: PlatformChatStreamOutputTextDoneTypedDict
    id: NotRequired[str]
    event: Literal["RESPONSE_OUTPUT_TEXT_DONE"]


class PlatformChatStreamOutputTextDoneServerSentEvent(BaseModel):
    data: PlatformChatStreamOutputTextDone

    id: Optional[str] = None

    EVENT: Annotated[
        Annotated[
            Literal["RESPONSE_OUTPUT_TEXT_DONE"],
            AfterValidator(validate_const("RESPONSE_OUTPUT_TEXT_DONE")),
        ],
        pydantic.Field(alias="event"),
    ] = "RESPONSE_OUTPUT_TEXT_DONE"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    PlatformChatStreamOutputTextDoneServerSentEvent.model_rebuild()
except NameError:
    pass
