"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .platformchatinputmessage import (
    PlatformChatInputMessage,
    PlatformChatInputMessageTypedDict,
)
from glean.api_client.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


InputTypedDict = TypeAliasType(
    "InputTypedDict", Union[str, List[PlatformChatInputMessageTypedDict]]
)
r"""Either a plain string (single user turn) or a chronological array of `user`/`assistant` messages. The final array message must be `user`.

"""


Input = TypeAliasType("Input", Union[str, List[PlatformChatInputMessage]])
r"""Either a plain string (single user turn) or a chronological array of `user`/`assistant` messages. The final array message must be `user`.

"""


class PlatformChatCreateRequestTypedDict(TypedDict):
    input: InputTypedDict
    r"""Either a plain string (single user turn) or a chronological array of `user`/`assistant` messages. The final array message must be `user`.

    """
    stream: NotRequired[bool]
    r"""When true, respond with `text/event-stream`. When false or omitted, respond with `application/json`.

    """
    store: NotRequired[bool]
    r"""When true (default), persist the interaction and return a `conversation_id`. When false, run ephemerally with no persistence.

    """
    conversation_id: NotRequired[str]
    r"""Continue an existing stored conversation. Incompatible with message-array `input` and with `store: false`.

    """


class PlatformChatCreateRequest(BaseModel):
    input: Input
    r"""Either a plain string (single user turn) or a chronological array of `user`/`assistant` messages. The final array message must be `user`.

    """

    stream: Optional[bool] = False
    r"""When true, respond with `text/event-stream`. When false or omitted, respond with `application/json`.

    """

    store: Optional[bool] = True
    r"""When true (default), persist the interaction and return a `conversation_id`. When false, run ephemerally with no persistence.

    """

    conversation_id: Optional[str] = None
    r"""Continue an existing stored conversation. Incompatible with message-array `input` and with `store: false`.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["stream", "store", "conversation_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
