"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class PlatformSkillUpdateStatus(str, Enum):
    r"""Activation to apply for the authenticated caller. For the owner, this updates the skill's stored status. For any other caller, it updates only that caller's setting."""

    ENABLED = "ENABLED"
    DISABLED = "DISABLED"
