"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from glean.api_client.types import BaseModel
from typing_extensions import TypedDict


class PlatformAgentRunCancellationRequestTypedDict(TypedDict):
    r"""Request cooperative cancellation of a run owned by the caller."""

    run_id: str
    r"""ID of the run to cancel. Must belong to the agent identified in the path."""


class PlatformAgentRunCancellationRequest(BaseModel):
    r"""Request cooperative cancellation of a run owned by the caller."""

    run_id: str
    r"""ID of the run to cancel. Must belong to the agent identified in the path."""
