"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from glean.api_client.types import BaseModel
from glean.api_client.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class PlatformSkillsSyncRequestTypedDict(TypedDict):
    skill_id: str
    r"""ID of the GitHub-imported skill to sync."""


class PlatformSkillsSyncRequest(BaseModel):
    skill_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""ID of the GitHub-imported skill to sync."""
