"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .debugdocumentlifecyclerequest import (
    DebugDocumentLifecycleRequest,
    DebugDocumentLifecycleRequestTypedDict,
)
from glean.api_client.types import BaseModel
from glean.api_client.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class PostAPIIndexV1DebugDatasourceDocumentEventsRequestTypedDict(TypedDict):
    datasource: str
    r"""The datasource to which the document belongs"""
    debug_document_lifecycle_request: DebugDocumentLifecycleRequestTypedDict


class PostAPIIndexV1DebugDatasourceDocumentEventsRequest(BaseModel):
    datasource: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The datasource to which the document belongs"""

    debug_document_lifecycle_request: Annotated[
        DebugDocumentLifecycleRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
