"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .scopetype import ScopeType
from glean.api_client import models
from glean.api_client.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import field_serializer, model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ReadPermissionTypedDict(TypedDict):
    r"""Describes the read permission level that a user has for a specific feature"""

    scope_type: NotRequired[ScopeType]
    r"""Describes the scope for a ReadPermission, WritePermission, or GrantPermission object"""


class ReadPermission(BaseModel):
    r"""Describes the read permission level that a user has for a specific feature"""

    scope_type: Annotated[Optional[ScopeType], pydantic.Field(alias="scopeType")] = None
    r"""Describes the scope for a ReadPermission, WritePermission, or GrantPermission object"""

    @field_serializer("scope_type")
    def serialize_scope_type(self, value):
        if isinstance(value, str):
            try:
                return models.ScopeType(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["scopeType"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    ReadPermission.model_rebuild()
except NameError:
    pass
