"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from glean.api_client import utils


class ScopeType(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Describes the scope for a ReadPermission, WritePermission, or GrantPermission object"""

    GLOBAL = "GLOBAL"
    OWN = "OWN"
