"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .datasourceinstanceconfiguration import (
    DatasourceInstanceConfiguration,
    DatasourceInstanceConfigurationTypedDict,
)
from glean.api_client.types import BaseModel
from typing_extensions import TypedDict


class UpdateDatasourceConfigurationRequestTypedDict(TypedDict):
    r"""Request to update greenlisted configuration values for a datasource instance. Only keys that are exposed via the public API greenlist may be set."""

    configuration: DatasourceInstanceConfigurationTypedDict
    r"""Configuration for a datasource instance"""


class UpdateDatasourceConfigurationRequest(BaseModel):
    r"""Request to update greenlisted configuration values for a datasource instance. Only keys that are exposed via the public API greenlist may be set."""

    configuration: DatasourceInstanceConfiguration
    r"""Configuration for a datasource instance"""
