"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from glean.api_client import utils


class UploadStatusEnum(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Upload status, enum of NOT_UPLOADED, UPLOADED, STATUS_UNKNOWN"""

    UPLOADED = "UPLOADED"
    NOT_UPLOADED = "NOT_UPLOADED"
    STATUS_UNKNOWN = "STATUS_UNKNOWN"
