"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from glean.api_client import models, utils
from glean.api_client.types import BaseModel, UNSET_SENTINEL
from pydantic import field_serializer, model_serializer
from typing import Optional, TYPE_CHECKING
from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    from .verificationmetadata import (
        VerificationMetadata,
        VerificationMetadataTypedDict,
    )


class State(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The verification state for the document."""

    UNVERIFIED = "UNVERIFIED"
    VERIFIED = "VERIFIED"
    DEPRECATED = "DEPRECATED"


class VerificationTypedDict(TypedDict):
    state: State
    r"""The verification state for the document."""
    metadata: NotRequired["VerificationMetadataTypedDict"]


class Verification(BaseModel):
    state: State
    r"""The verification state for the document."""

    metadata: Optional["VerificationMetadata"] = None

    @field_serializer("state")
    def serialize_state(self, value):
        if isinstance(value, str):
            try:
                return models.State(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["metadata"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
