"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .objectpermissions import ObjectPermissions, ObjectPermissionsTypedDict
from .person import Person, PersonTypedDict
from glean.api_client.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class WorkflowTypedDict(TypedDict):
    name: NotRequired[str]
    r"""The name of the workflow."""
    author: NotRequired[PersonTypedDict]
    create_timestamp: NotRequired[int]
    r"""Server Unix timestamp of the creation time."""
    last_update_timestamp: NotRequired[int]
    r"""Server Unix timestamp of the last update time."""
    last_draft_saved_at: NotRequired[int]
    r"""Server Unix timestamp of the last time the draft was saved."""
    last_draft_saved_by: NotRequired[PersonTypedDict]
    last_draft_git_author_id: NotRequired[str]
    r"""ID of the VCS user (e.g. GitHub username) who last saved the draft. Set only by the draft save path via the external Git integration API."""
    last_updated_by: NotRequired[PersonTypedDict]
    permissions: NotRequired[ObjectPermissionsTypedDict]
    id: NotRequired[str]
    r"""The ID of the workflow."""
    verified: NotRequired[bool]
    r"""When present, indicates this workflow is admin-verified. Set via the dedicated admin settings endpoint, not by regular edits."""
    show_organization_as_author: NotRequired[bool]
    r"""When true, displays organization name instead of author name in agent card. Set via the dedicated admin settings endpoint, not by regular edits."""


class Workflow(BaseModel):
    name: Optional[str] = None
    r"""The name of the workflow."""

    author: Optional[Person] = None

    create_timestamp: Annotated[
        Optional[int], pydantic.Field(alias="createTimestamp")
    ] = None
    r"""Server Unix timestamp of the creation time."""

    last_update_timestamp: Annotated[
        Optional[int], pydantic.Field(alias="lastUpdateTimestamp")
    ] = None
    r"""Server Unix timestamp of the last update time."""

    last_draft_saved_at: Annotated[
        Optional[int], pydantic.Field(alias="lastDraftSavedAt")
    ] = None
    r"""Server Unix timestamp of the last time the draft was saved."""

    last_draft_saved_by: Annotated[
        Optional[Person], pydantic.Field(alias="lastDraftSavedBy")
    ] = None

    last_draft_git_author_id: Annotated[
        Optional[str], pydantic.Field(alias="lastDraftGitAuthorId")
    ] = None
    r"""ID of the VCS user (e.g. GitHub username) who last saved the draft. Set only by the draft save path via the external Git integration API."""

    last_updated_by: Annotated[
        Optional[Person], pydantic.Field(alias="lastUpdatedBy")
    ] = None

    permissions: Optional[ObjectPermissions] = None

    id: Optional[str] = None
    r"""The ID of the workflow."""

    verified: Optional[bool] = None
    r"""When present, indicates this workflow is admin-verified. Set via the dedicated admin settings endpoint, not by regular edits."""

    show_organization_as_author: Annotated[
        Optional[bool], pydantic.Field(alias="showOrganizationAsAuthor")
    ] = None
    r"""When true, displays organization name instead of author name in agent card. Set via the dedicated admin settings endpoint, not by regular edits."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "name",
                "author",
                "createTimestamp",
                "lastUpdateTimestamp",
                "lastDraftSavedAt",
                "lastDraftSavedBy",
                "lastDraftGitAuthorId",
                "lastUpdatedBy",
                "permissions",
                "id",
                "verified",
                "showOrganizationAsAuthor",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    Workflow.model_rebuild()
except NameError:
    pass
