name: Patch Speakeasy PR

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'src/glean/__init__.py'

jobs:
  add-extend-path:
    if: contains(github.event.pull_request.title, 'Update SDK - Generate')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Patch glean/__init__.py with extend_path
        id: patch
        run: |
          OUTPUT=$GITHUB_OUTPUT .github/scripts/patch_extend_path.sh

      - name: Commit and push if file changed
        if: steps.patch.outputs.patched == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add src/glean/__init__.py
          git commit -m "ci: ensure extend_path lines in glean/__init__.py" || echo "No changes to commit"
          git push 